### ISSUE TITLE
Action State and Buttons

### ISSUE THREAD

**Issue by DonnySolana** [solana-labs/dapp-scaffold#150]
Currently actions triggered by buttons are stateless. When you click to send a transaction the user is not aware if anything happened until the actions responds from the call being made. There could be a few approaches to solving this issue.

Solution Ideas:

In the case of a button,

- Manage action states in such a way that when clicked the button state is disabled until a response is received and then re enabled. 
- Additionally produce an optional busy or spinner/loading modal that shows the user the transaction is processing and optionally automatically closes when done.

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by DonnySolana** [comment]
thank you for the submission. please re request with the latest if desired to submit. thank you!
