### ISSUE TITLE
Use Chakra-UI Instead of Tailwind

### ISSUE THREAD

**Issue by mattruddy** [solana-labs/dapp-scaffold#162]
Why tailwind?

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by DonnySolana** [comment]
propose a branch for chakra if you like. this is not a constructive issue.
