### ISSUE TITLE
Transaction creation failed.

### ISSUE THREAD

**Issue by breadbaker** [solana-labs/dapp-scaffold#173]
Just trying the out of the box transaction an error:

`Phantom - RPC Error: Transaction creation failed. {code: -32003, message: 'Transaction creation failed.'}`

**Comment by beamsies** [comment]
Same issue on my end

**Comment by itskamalhere** [comment]
Faced the same issue and increased the lamport value(i tried with 1 Billion Lamport) to higher value and ot worked.
Note: 1 Sol = 1 Billion Lamport and so transaction of 1 Lamport is failing i guess.
