### ISSUE TITLE
Eslint config

### ISSUE THREAD

**Issue by haodev007** [solana-labs/dapp-scaffold#184]
Let us config eslint to match coding style to contribute!
Please add public code style in .eslintrc.json file
And please add this line in scripts of package.json file as a command
"lint:fix": "next lint -- --fix"
by using this command, we can match code style automatically when commit or create PR after changing the file.

Thanks!

**Comment by DonnySolana** [comment]
please submit a recommendation and we will take it under advisement. thank you for the suggestion.
