### ISSUE TITLE
"Expired transaction" - ERROR

### ISSUE THREAD

**Issue by mrbotnft** [solana-labs/dapp-scaffold#257]
We are getting "expired transaction error" in phatom while trying to send any transaction in the devnet or testnet. Signing a message works fine. It pop ups the error without any possibility to click the approve button or anything. This doesn't happen in the mainnet weirdly, just the other 2 nets.

**Comment by mrbotnft** [comment]
Found the bug:

` const transaction = new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: publicKey,
          toPubkey: Keypair.generate().publicKey,
          lamports: 1_000_000,
        })
      );

      const {
        context: { slot: minContextSlot },
        value: { blockhash, lastValidBlockHeight },
      } = await connection.getLatestBlockhashAndContext();

      signature = await sendTransaction(transaction, connection, {
        minContextSlot,
      });

      await connection.confirmTransaction({
        blockhash,
        lastValidBlockHeight,
        signature,
      });`

You are missing this in the SendTransaction.tsx. Check @solana-wallet-adapter for refence

**Comment by mrbotnft** [comment]
https://github.com/solana-labs/dapp-scaffold/pull/258

**Comment by DonnySolana** [comment]
issue should be resolved in latest. please re-request if necessary. thank you!
