### ISSUE TITLE
Default token mints subscriptions, killer for public rpc and private pools

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/dapp-scaffold#27]
Every single token mint in spl-token-registry is added to the cache

https://github.com/solana-labs/dapp-scaffold/blob/9352c93fe34fb061eed33030dc406074295a69b0/src/contexts/connection.tsx#L97-L125

Adding to the cache has a side effect, creating a subscription to the added account:
https://github.com/solana-labs/dapp-scaffold/blob/eef68f4a46717b81549211594334d98bf358f87d/src/contexts/accounts.tsx#L361-L371

This problem is invisible on devnet as the token list is small, but once plugged to mainnet this is a node/rpcpool killer as the code will open a great number of account subscriptions through `onAccountChange`

In most cases an up to date token mint is not required, only in rare cases it is useful (LP token supply...).

This should be reworked so the dapp-scaffold boilerplate is not a trap.

Here is a screenshot of the swarm of accountSubscribe in the websocket, it can't even fit on the screen
![Screenshot from 2021-07-22 18-39-12](https://user-images.githubusercontent.com/8245419/126722981-d3d2152a-a61d-47a2-83e4-63ca2f4fad4c.png)

Some of which are essential tokens to be monitored
![Screenshot from 2021-07-22 17-54-47](https://user-images.githubusercontent.com/8245419/126723060-51e8a7ce-0dfd-4d64-aaab-59b90b514cae.png)

**Comment by brianlong** [comment]
I'll upvote the importance of this issue. We have now seen multiple cases where developers started with this scaffold and later saw disastrous results on their mainnet launch. Blindly opening this many subscriptions is an anti-pattern to be avoided.

A safer approach might be for the developer to explicitly state the subscriptions they require.

// @bartosz-lipinski @rmshea

**Comment by joeaba** [comment]
+ @bhgames

**Comment by aaronovz1** [comment]
Can confirm this is a node killer. It's better to get rid of subscriptions altogether and just poll at reasonable frequencies using `getMultipleAccounts` to batch as much as you can.

**Comment by kevinrodriguez-io** [comment]
I'll take a look into this.
