### ISSUE TITLE
 Hydration error on page load when wallet is autoconnected

### ISSUE THREAD

**Issue by josip-volarevic** [solana-labs/dapp-scaffold#276]
`WalletModalProvider` should be dynamically loaded, without ssr

### Reproduction

https://user-images.githubusercontent.com/34980162/198713410-90566d0b-5e60-4c7e-aeac-8ec29296c146.mp4

**Comment by curtislbyrd** [comment]
I'm getting the same error. It looks like it doesn't like the <i> tags in Button.js or tsx in my case.

https://github.com/solana-labs/wallet-adapter/blob/master/packages/ui/react-ui/src/Button.tsx

next-dev.js?3515:20 Warning: Expected server HTML to contain a matching <i> in <button>.
