### ISSUE TITLE
No support for wallet standard?

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/dapp-scaffold#330]
Have just got this running, was expecting something like https://solana-labs.github.io/wallet-adapter/example/:

![image](https://user-images.githubusercontent.com/172594/229097408-9e95bf2c-080b-4856-8c94-b9e66ae5e2f1.png)

But although I have a wallet registered it won't show in this app:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/172594/229519716-963a6904-46df-480c-9378-7aaddda6126d.png">

Does dApp scaffold support wallet standard?

**Edit**: originally pasted the wrong screenshot. Now fixed.

**Comment by DonnySolana** [comment]
Are you getting the same result from the official dapp scaffold?  The screenshot above is from a svelte scaffold that is not related.

**Comment by mikemaccana** [comment]
Sorry Donny - I'd pasted the wrong screenshot (I was filing a similar issue with another project that had the same problem). I've since pasted the correct one. 

This does affect `dapp-scaffold` - specifically  `dapp-scaffold` isn't showing wallet's that have been registered with `registerWallet()` from the wallet standard. https://github.com/solana-labs/wallet-standard/blob/master/packages/wallets/ghost/src/register.ts#L11

**Comment by DonnySolana** [comment]
what is the 'code' difference in the scaffold wallet support and the example in the wallet adapter demo your referencing? The scaffold contains a burner wallet and does load additional wallets.  Is there a difference you notice you can PR or specific wallet you have an issue with? Curious what you have tried and if you are unable to PR if there is a fix?

**Comment by mcintyre94** [comment]
I can't repro this. If I start `dapp-scaffold` then I can connect to phantom, glow or backpack. Speculation based on your screenshots, is it possible that something is stopping your `Portal` wallet from registering on localhost? Can you verify somehow that it definitely is being registered correctly?

**Comment by DonnySolana** [comment]
@mikemaccana are you still having an issue or have reproduceable steps here? It seems this issue cannot be reproduced. Were you able to narrow down or manage to resolve this issue, if so how?  thanks!
