### ISSUE TITLE
[ui] transaction notifications have no background

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/dapp-scaffold#340]
The transaction notifications do not show with a background. So they seem to float over the rest of the page

![image](https://user-images.githubusercontent.com/75431177/235734545-b31aafec-d645-4159-a3a0-2de715e3847b.png)

**Comment by YTW7** [comment]
hello nick, could you assign this task to me?

**Comment by YTW7** [comment]
Made a quick PR for the same, could you please take a look and maybe merge it: https://github.com/solana-labs/dapp-scaffold/pull/341
