### ISSUE TITLE
Deployed an NFT Collection using this dapp and got baned

### ISSUE THREAD

**Issue by csa1234** [solana-labs/dapp-scaffold#360]
Just to let you know, I deployed a 15k NFT Collection using the readme and guide from this Github
Deployed at Vercel https://capitolchilax.vercel.app

The smartcontract was done using Metaplex Sugar Candy Machine with a cost of nearly 1000 USDT due to high volume of 15k NFTs
And getting banned and tagged by Phantom, Solflare and even Crossmint as malicious code.

I sent Phantom all my social media links so they can verify im not a scamer and a real NFT artist and developer, and they keep asking me someone from Solana Dev team to refer me... WTF? 

After costing me over 1500 USDT between Candy Machine and Irys/Bundlr images i get tagged and my dapp (yes this dapp) banned

![solana 1](https://github.com/solana-labs/dapp-scaffold/assets/55300277/640aee2a-a3ff-4120-963c-1daca2ac05f7)
![solana 2](https://github.com/solana-labs/dapp-scaffold/assets/55300277/89b7048d-ec57-4eca-af01-7935d7a64b43)
![solana3](https://github.com/solana-labs/dapp-scaffold/assets/55300277/0ef7bc60-9fcd-4c29-a187-178a0e66df9b)
![solana4](https://github.com/solana-labs/dapp-scaffold/assets/55300277/94e6c2a9-9004-4cb1-9e45-566f629b3cee)
![solana5](https://github.com/solana-labs/dapp-scaffold/assets/55300277/6c0e5eea-1334-4a91-badd-779951c490e3)

Im making public all this situation, as i find my self without option. I dont know anyone from Solana lab, I dont know anyone from Ethereum team development.... im just a guy, who took over 5 months of work creating, developing and designing the NFTs all by myself, used over 1500 USDT of my own funds and then get tagged like if im a malicious, rug scamer guy... WTF ? its really discouraging developing in this kind of enviroment, so im making public all this, so maybe I can call the attention of someone from Solana development team and help me out what on earth one have to do to deploy a an NFT minting project

Sorry if I sound pissed... its just been so discouraging putting so much effort to get stoped over and over

**Comment by 0xGRAV3R** [comment]
So sorry to hear this tbh I understand your concerns about the process—it can feel less than ideal for a truly permission-less system. Currently, this is the approach Phantom has implemented, likely to mitigate potential risks from malicious actors. We've followed this process ourselves, and while it isn't entirely aligned with the permission-less ethos, we complied and received a response from the Blowfish team. Their support has been responsive and helpful, so overall, our experience has been positive so far. I hope this helps clarify things!
