### ISSUE TITLE
Phantom icon

### ISSUE THREAD

**Issue by Mitolius** [solana-labs/dapp-scaffold#48]
Hi,

Why don't I have the Phantom icon ? (got all the other ones)

![image](https://user-images.githubusercontent.com/6568374/131932912-6b5ecfc6-1db1-4ef1-a5af-ac926a6af1c9.png)

Thanks

**Comment by walter-grace** [comment]
> Hi,
> 
> Why don't I have the Phantom icon ? (got all the other ones)
> 
> ![image](https://user-images.githubusercontent.com/6568374/131932912-6b5ecfc6-1db1-4ef1-a5af-ac926a6af1c9.png)
> 
> Thanks

Same, I am getting this error as well

**Comment by Mitolius** [comment]
It seems that URL return 404:

https://raw.githubusercontent.com/solana-labs/wallet-adapter/master/packages/wallets/icons/phantom.png

Don't know how to fix :(
