### ISSUE TITLE
TypeError: naclLowLevel.gf is not a function

### ISSUE THREAD

**Issue by Yuvasee** [solana-labs/dapp-scaffold#50]
I've done everything according to readme and after `yarn start` in browser I got this:
![image](https://user-images.githubusercontent.com/7745709/132020111-39b45a89-109e-488a-a6e1-5fc6b888d704.png)

I got the same issue when tried to use https://github.com/GokiProtocol/walletkit for my project. There I fixed it by changing solana related dependencies versions from 0.16.0 to 0.14.2.

**Comment by rainbowemoji** [comment]
I have the same issue.
What does solana related dependency mean here?
Is it node version?
How can I change it?

**Comment by shivekkhurana** [comment]
I was able to fix the issue by installing `tweetnacl` package.
