### ISSUE TITLE
Basic example of storing a data on a hash table / key value pair

### ISSUE THREAD

**Issue by ashr1987** [solana-labs/dapp-scaffold#52]
Hi there - I've been trying to find a basic example of Solana + React to do the basics of a CRUD web app. From React through to Rust contract:

- Register a new user e.g. `registerUser(string userName)` stores `userName` against the users public address in a hashset/hashtable/keyvaluepair in Rust, returns a new unique userId e.g. int64
- Lookup a "record" (e.g.`user`/`customer`/`order`) via `lookupCustomer(int customerId)`, returns plain javascript object e.g. `{ "firstName": "Ash", "lastName": "Rudland" }`, assuming this could be a hashtable/hashset/keyvaluepair too.

I gave up after a few weeks, would really help so many of us app developers getting into Solana and just trying to find a simple example of what we would like to build.

Thanks!

**Comment by tyntyn1** [comment]
> Xin chào - Tôi đang cố gắng tìm một ví dụ cơ bản về Solana + React để thực hiện những điều cơ bản về ứng dụng web CRUD. Từ React đến Rust contract:
> 
> * Đăng ký người dùng mới, ví dụ: `registerUser(string userName)`lưu trữ `userName`đối với địa chỉ công khai của người dùng trong cặp băm / hashtable / keyvaluepair trong Rust, trả về userId duy nhất mới, ví dụ int64
> * Tra cứu một "bản ghi" (ví dụ `user`/ `customer`/ `order`) qua `lookupCustomer(int customerId)`, trả về đối tượng javascript thuần `{ "firstName": "Ash", "lastName": "Rudland" }`, ví dụ: giả sử đây cũng có thể là một cặp băm / hashset / keyvaluepair.
> 
> Tôi đã bỏ cuộc sau một vài tuần, thực sự sẽ giúp rất nhiều nhà phát triển ứng dụng trong chúng tôi tham gia vào Solana và chỉ cố gắng tìm một ví dụ đơn giản về những gì chúng tôi muốn xây dựng.
> 
> Cảm ơn!
