### ISSUE TITLE
how do you debug on vscode with CodeLLDB , cargo test-bpf failing

### ISSUE THREAD

**Issue by goldcoders** [solana-labs/dapp-scaffold#58]
Hi im trying to use Debug on VSCode on Mac M1

- rustc 1.55.0
- rustup 1.24.3
- cargo 1.55.0
- solana 1.7.12

I need to find out what is the executable file generated ,
there is no .dmg or .app so i dont think there is a executable generated

i did run cargo build and cargo build-bpf (prior version of solana 1.7.11 is failing installed in brew)
it generated *.so file needed to be deploy on the test network.
I manage to upload it 

this is my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "(Mac M1) Launch",
            "host": "arm64",
            // update this to point to the executable
            "program": "${workspaceFolder}/program/target/debug/${DONT KNOW WHAT EXECUTABEL TO PUT HERE}",
            "args": [],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

Here is the File Structure in my Mac M1:

<img width="554" alt="Screen Shot 2021-09-19 at 10 33 48 PM" src="https://user-images.githubusercontent.com/55337687/133931455-34abfa5a-205d-47b7-be83-0997c2699521.png">

I also faced issue on running 

cargo test-bpf

which i think also other people here is facing...

**Comment by Boiethios** [comment]
Same problem here. There is an error originating from the Solana code, and I'd like to put a breakpoint, see the variables values, etc. I've tried to attach the CLion debugger to the cargo-test-bpf process, but that doesn't work, due to the bin format, I guess.

**Comment by peteoleary** [comment]
I have been trying to debug tests with this launch.json config:

```
{
            "type": "lldb",
            "request": "launch",
            "name": "Debug unit tests",
            "cargo": {
                "args": [
                    "test-bpf",
                    "--no-run"
                ]
            },
            "args": [],
            "cwd": "${workspaceFolder}/program"
        }
```

but I get an error:

```
Running `cargo test-bpf --no-run --message-format=json`...
error: Found argument '--message-format' which wasn't expected, or isn't valid in this context
```

Something in VS Code is adding `--message-format=json` and I can't figure out what.

Let me know if you guys make any progress on this.
