### ISSUE TITLE
Unhandled Rejection: Not a valid Mint

### ISSUE THREAD

**Issue by 3mp8r3** [solana-labs/dapp-scaffold#87]
![image](https://user-images.githubusercontent.com/3013114/144738854-b02633df-0ecc-4792-ae03-d0ae96094fb5.png)

**Comment by BMonsalvatge** [comment]
Getting the same error when starting a new project.

**Comment by endel** [comment]
Having the same after a fresh install. Any ideas?

**Comment by JimLynchCodes** [comment]
same... 😢

**Comment by cuongn265** [comment]
Try this https://github.com/solana-labs/dapp-scaffold/pull/66#issuecomment-934702192
