### ISSUE TITLE
Wallet connect issue on mobiles.

### ISSUE THREAD

**Issue by cryptoSyndrome001** [solana-labs/dapp-scaffold#97]
I can't connect to wallet just like Phantom on mobiles.
I searched the way, but not found out yet.

**Comment by ZENX0x2** [comment]
May the force be with you on your quest to find the way.

**Comment by fusunnn** [comment]
I don't think it's possible to implement Phantom wallet on mobile as it is an extension that you have to add to your browser, and Safari does not support extensions on mobile (Phantom isn't even on Safari for Macs) and I don't think Chrome supports extensions on mobile. Please do tell me if I am wrong about this though.
